public enum Opciones {
    RENDIRSE,
    ATAQUE,
    CAMPOBATALLA,
    POKEMONS,
    INTERCAMBIAR_POKEMON,
    HABILIDADES,
    SELECCION_HABILIDAD,
    ITEMS,
    SELECCION_ITEM,
    APLICAR_ITEM,
}
